### ISSUE TITLE
Extend the validation webhook to fully validate cloud profile and shoot resources

### ISSUE THREAD

**Issue by stoyanr** [gardener/gardener-extension-provider-kubevirt#39]
The current validation webhook (or "validator") introduced with #11 does not validate all configuration settings that could be found in the cloud profile and shoot resources. It should be extended to validate:

* Cloud profile `machineTypes`
* Shoot `provider.infrastructureConfig.networks`, introduced with #16
* Cloud profile `providerConfig` (if it has been extended with #36).
* Shoot `provider.workers[n].providerConfig` (if it has been extended with #36)

/area usability
/kind enhancement
/priority normal
/platform kubevirt

**Comment by mfranczy** [comment]
What kind of validation & verification strategy we want to provide? Since KubeVirt has its own validation webhooks, I would go only with verification strategy that fields set by users are correct. To give you an example, let's say that a new user is setting a hugepage size 1Gi and we run VM which has 512Mi of memory. On our side we verify that that the value is in the correct format but we don't validate if user defined value is appropriate (in this case 1Gi > 512Mi), the information about inappropriate value will come directly from KubeVirt. In our case we provide information to user that format is correct or not, as quickly as possible. @stoyanr @moadqassem @mvladev any thoughts?

**Comment by mfranczy** [comment]
The above question is also with regards to mcm-provider-kubevirt.

**Comment by moadqassem** [comment]
>The above question is also with regards to mcm-provider-kubevirt.

For the mcm-kubevirt-provider the machine-server(aka plugin) is handling the validation of the spec upon vms creation/updating/ etc..thus we don't need anything over there.

**Comment by mfranczy** [comment]
> >   The above question is also with regards to mcm-provider-kubevirt.

> For the mcm-kubevirt-provider the machine-server(aka plugin) is handling the validation of the spec upon vms creation/updating/ etc..thus we don't need anything over there.

Yes, but still i have to validate machine class fields, so i could provide values validation not only verification, so I think this applies there too.
